version: 2.1
workflows:
  lint_and_test:
    jobs:
      - lint
      - contracts-test:
          context: web3-storage
      - circuits-test

# Just for reusing below
step_defs:
  - run: &node_version
      name: Set Node version
      command: |
        nvm install v18.15
        nvm alias default v18.15
        echo "nvm use default" >> $BASH_ENV
  - run: &check_version
      name: Check Node version
      command: node -v | grep v18
  - run: &download_circom
      name: Download Circom
      command: |
        sudo wget -O /usr/bin/circom https://github.com/iden3/circom/releases/download/v2.1.5/circom-linux-amd64
        sudo chmod +x /usr/bin/circom
        circom --version
  - run: &install_circom
      name: Install Circom
      command: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source "$HOME/.cargo/env"
        cd /tmp
        git clone https://github.com/iden3/circom.git
        cd circom
        cargo build --release
        cargo install --path circom
        circom --version

jobs:
  lint:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: medium
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: yarn
      - run:
          name: Lint
          command: yarn lint --check
  contracts-test:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run: *download_circom
      - run:
          name: Install
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test:contracts:coverage
      - run:
          name: Upload Coverage
          command: node scripts/uploadCoverage.mjs
      - run:
          name: Badge Purge
          command: npx camo-purge@1.0.2 --repository https://github.com/unirep/auth
  circuits-test:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run: *download_circom
      - run:
          name: Install
          command: yarn
      - run:
          name: Build
          command: yarn build:circuits
      - run:
          name: Test
          command: yarn test:circuits
